name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v16.14.0
      uses: actions/setup-node@v1
      with:
        node-version: '16.14.0'
    - run: npm install
    - run: npm run test